/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        'surface': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#494552',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'outline': '#7a7583',
        'outline-variant': '#cac4d4',
        'surface-tint': '#2563EB',
        'primary': '#2563EB',
        'on-primary': '#ffffff',
        'primary-container': '#a78bfa',
        'on-primary-container': '#3c1989',
        'inverse-primary': '#cebdff',
        'secondary': '#0060ac',
        'on-secondary': '#ffffff',
        'secondary-container': '#64a8fe',
        'on-secondary-container': '#003c70',
        'tertiary': '#006c4b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00b37e',
        'on-tertiary-container': '#003d28',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e8ddff',
        'primary-fixed-dim': '#cebdff',
        'on-primary-fixed': '#21005e',
        'on-primary-fixed-variant': '#4f319c',
        'secondary-fixed': '#d4e3ff',
        'secondary-fixed-dim': '#a4c9ff',
        'on-secondary-fixed': '#001c39',
        'on-secondary-fixed-variant': '#004883',
        'tertiary-fixed': '#68fcbf',
        'tertiary-fixed-dim': '#45dfa4',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005137',
        'background': '#f8f9fa',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4'
      }
    },
  },
  plugins: [],
}